Add CURL support for HTTPS connection
secure-device-onboard/client-sdk-fidoiot pull request #188
Opened 2022-07-18 16:13 UTC by shrikant1407

Add CURL support for HTTPS connection

Signed-off-by: Shrikant Temburwar <shrikant.temburwar@intel.com>

2022-07-19 10:20 UTC, vikashmishra07 approved these changes
Please update the readme for self signed certificate in respect to security consequence...

2022-07-19 11:52 UTC, KiranSukhavasi requested changes
hold on till FDO 1.1.0.3 release

2022-07-25 10:49 UTC, tajnisha commented on cmake/cli_input.cmake
> -# FOR PROXY_DISCOVERY
Please retain PROXY_DISCOVERY as discussed.

2022-07-25 10:49 UTC, tajnisha commented on lib/fdonet.c
> +		    "Invalid Proxy Connection info for Manufacturer server!\n");
Update the log message as "setting up proxy for MFG failed".

2022-07-25 10:49 UTC, tajnisha commented on lib/fdoprotctx.c
> +					      &msglen, prot_ctx->ssl, tmp_buf, &ctr);
Can tmp_buf be renamed as curl_buf and ctr as curl_buf_offset at all places ?

2022-07-26 09:07 UTC, tajnisha commented on lib/fdonet.c
> +		    "Invalid Proxy Connection info for Manufacturer server!\n");
Apply above for rv and owner function as well.

2022-07-27 08:01 UTC, shrikant1407 commented on network/network_if_linux.c
> -		if (fdo_ssl_connect(*ssl)) {
It is still needed to pass unit tests

2022-07-28 06:04 UTC, tajnisha commented on app/main.c
> +	if  (argc > 1 && (strcmp_ss || strcmp_ss2)) {
[out] | indicator | pointer to result indicator, greater than 0, equal to 0 or less than 0, if the string pointed to by dest is greater than, equal to or less than the string pointed to by src respectively.

Looks like the expected value of the 4th argument strcmp_ss is zero ?

2022-07-29 05:18 UTC, tajnisha submitted a review, later dismissed

2022-08-02 05:51 UTC, himanshu7196 approved these changes

2022-08-02 05:59 UTC, KiranSukhavasi approved these changes

2022-08-02 06:07 UTC, merged