Update README
secure-device-onboard/client-sdk-fidoiot pull request #39
Opened 2021-04-05 16:22 UTC by prateekcr

Updating README to reflect the changes made in this release.

Signed-off-by: Chandrakar, Prateek <prateek.chandrakar@intel.com>

2021-04-06 10:00 UTC, trbehera approved these changes

2021-04-06 10:01 UTC, trbehera requested changes
Needs some more change.

2021-04-06 14:51 UTC, prateekcr commented on README.md
> +- [ TinyCBOR ](docs/setup.md#tinycbor) <br>
There was no such section in setup.md. This was a broken link that has been removed.

2021-04-06 14:52 UTC, prateekcr commented
All comments, except 1, have been updated in the commit.

2021-04-06 15:36 UTC, trbehera approved these changes

2021-04-07 05:51 UTC, KiranSukhavasi approved these changes
take car3 of tushar's comments and otherwise good to go.

2021-04-07 06:59 UTC, merged