Update comments for KDF and protocol messages
secure-device-onboard/client-sdk-fidoiot pull request #89
Opened 2021-06-01 06:37 UTC by prateekcr

Signed-off-by: Chandrakar, Prateek <prateek.chandrakar@intel.com>

2021-06-01 08:32 UTC, trbehera requested changes
Few more occurrences of msg4x / msg5x comments.

lib/prot/to2/msg61.c:292:               LOG(LOG_INFO, "No Ownership Vouchers, jumping to **msg44**\n");
lib/prot/to2/msg69.c:16: * **msg49**() - TO2.OwnerServiceInfo
lib/fdoprot.c:225:              /* If we reached with **msg51** as ps->state, we are done */

2021-06-01 08:32 UTC, trbehera commented on crypto/common/fdoKeyExchange.c
> +	kdf_input[ofs++] = 0x00;	// separation indicator
For uniformity, add the comment line above the actual statement.

// separation indicator
kdf_input[ofs++] = 0x00;

2021-06-01 08:32 UTC, trbehera commented on crypto/common/fdoKeyExchange.c
> +	uint8_t *kdf_input = NULL;	// input data to the KDF
Same as above for comments.

2021-06-01 08:48 UTC, trbehera approved these changes

2021-06-08 16:14 UTC, johneasterday approved these changes

2021-06-09 07:13 UTC, merged